name: EC2 Docker Setup

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo (to get the .pem file)
      - name: Checkout repo
        uses: actions/checkout@v4

      # Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Show Node.js version
        run: node -v

      # Show AWS CLI version (already installed on GitHub runner)
      - name: Show AWS CLI version
        run: aws --version

      # SSH into EC2 and install Docker + Docker Compose
      - name: Install Docker and Docker Compose on EC2
        run: |
          EC2_USER=ubuntu   # change if using Amazon Linux ("ec2-user")
          EC2_HOST=${{ secrets.EC2_PUBLIC_IP }}   # store EC2 public IP in secrets
          PEM_FILE=$(ls ./*.pem | head -n 1)

          ssh -o StrictHostKeyChecking=no -i "$PEM_FILE" $EC2_USER@$EC2_HOST << 'EOF'
            # Update packages
            sudo apt-get update -y

            # Install Docker
            sudo apt-get install -y docker.io
            sudo systemctl enable docker
            sudo systemctl start docker

            # Install Docker Compose plugin
            sudo apt-get install -y docker-compose-plugin

            # Show versions
            docker --version
            docker compose version
          EOF
