name: EC2 Docker Setup

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Save PEM file from GitHub Secret
      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_PEM_KEY }}" > ec2-key.pem
          chmod 600 ec2-key.pem

      # SSH into EC2, clone repo, and run docker compose
      - name: Deploy on EC2
        run: |
          EC2_USER=ubuntu   # or ec2-user if Amazon Linux
          EC2_HOST="ec2-13-232-238-63.ap-south-1.compute.amazonaws.com"
          GIT_REPO_URL="https://github.com/GargiSinghRao12/evershop.git"

          ssh -o StrictHostKeyChecking=no -i ec2-key.pem $EC2_USER@$EC2_HOST << EOF
            set -e

            # Update system
            sudo apt-get update -y

            # Install Docker if not installed
            if ! command -v docker &> /dev/null; then
              sudo apt-get install -y docker.io
              sudo systemctl enable docker
              sudo systemctl start docker
            fi

            # Install Docker Compose plugin if not installed
            if ! docker compose version &> /dev/null; then
              sudo apt-get install -y docker-compose-plugin
            fi

            # Clone or update repo
            if [ ! -d "app-repo" ]; then
              git clone $GIT_REPO_URL app-repo
            else
              cd app-repo && git pull origin main && cd ..
            fi

            # Go inside repo and run docker compose
            cd app-repo
            sudo docker compose down || true
            sudo docker compose up -d --build
          EOF
